import {test} from 'node:test';
import assert from 'node:assert/strict';
import {normalizeClient,publicSnapshot,metrics,resizeItems,itemsOf,agreementTerms,signatureOutdated,validateAmount,safeUrl,esc,newToken} from '../portal/data.js';
import {buildProjectReport} from '../portal/report.js';

const fixture=()=>normalizeClient({name:'Test client',email:'private@example.invalid',accessToken:'secret',internalNotes:'NEVER PUBLIC',projects:{p:{name:'Test project',rate:400,budget:800,status:'active',items:[{n:1,b:'Beagle',t:'First',s:'delivered',no:'PRIVATE NOTE',clientNote:'PUBLIC NOTE',dl:'https://example.invalid/video'},{n:2,b:'Poodle',s:'pending',deleted:true}],payments:[{amount:1000,date:'2026-09-23',type:'Advance',proofUrl:'https://example.invalid/proof.png'}],approvals:[{title:'Review',desc:'Details'}]}}},'test');

test('normalization assigns stable payment/approval IDs without mutating inputs',()=>{const c=fixture(),again=normalizeClient(c,'test');assert.deepEqual(c,again);assert.equal(c.projects.p.payments[0].id,'payment-p-0');assert.equal(c.projects.p.approvals[0].id,'approval-p-0');});
test('public projection excludes secrets, private notes, deleted rows and archived reviews',()=>{const c=fixture();c.trash.t={value:{id:'hidden'},records:[{id:'archived-project-request'}]};c.feedbackReviews={hidden:{response:'SECRET'},visible:{response:'Hello'},'archived-project-request':{response:'SECRET'}};const p=publicSnapshot(c,'test'),json=JSON.stringify(p);for(const secret of ['private@example.invalid','secret','NEVER PUBLIC','PRIVATE NOTE','SECRET','Poodle'])assert.ok(!json.includes(secret));assert.equal(p.projects.p.items.length,1);assert.equal(p.feedbackReviews.visible.response,'Hello');assert.deepEqual(p.approvalProjects,{'approval-p-0':'p'});});
test('archived client and paused link publish disabled snapshots',()=>{const c=fixture();c._deleted=true;assert.equal(publicSnapshot(c,'test').enabled,false);c._deleted=false;c.accessEnabled=false;assert.equal(publicSnapshot(c,'test').enabled,false);});
test('metrics handle archived rows, zero values and overpayment without inventing defaults',()=>{const p=fixture().projects.p;assert.deepEqual(metrics(p),{total:1,done:1,paid:1000,budget:800,due:-200,percent:100});p.budget=0;p.items=[];assert.equal(metrics(p).percent,0);assert.equal(metrics(p).due,-1000);assert.equal(validateAmount('0'),0);assert.throws(()=>validateAmount(-1));assert.throws(()=>validateAmount('bad'));});
test('resizing archives safely and new rows never reuse archived numbers',()=>{const p=fixture().projects.p;resizeItems(p,0);assert.equal(itemsOf(p).length,0);assert.equal(p.items.length,2);resizeItems(p,2);assert.deepEqual(itemsOf(p).map(i=>i.n),[3,4]);assert.throws(()=>resizeItems(p,1001));assert.throws(()=>resizeItems(p,1.2));});
test('terms comparison is order independent and detects actual changes',()=>{const p=fixture().projects.p;const sig={termsSnapshot:Object.fromEntries(Object.entries(agreementTerms(p)).reverse())};assert.equal(signatureOutdated(sig,p),false);p.budget=900;assert.equal(signatureOutdated(sig,p),true);assert.equal(signatureOutdated({},p),false);});
test('URLs and HTML are escaped, tokens are cryptographically long and unique',()=>{assert.equal(safeUrl('javascript:alert(1)'),'');assert.equal(safeUrl('file:///secret'),'');assert.equal(esc('<script>"&'),'&lt;script&gt;&quot;&amp;');const tokens=Array.from({length:100},newToken);assert.equal(new Set(tokens).size,100);assert.ok(tokens.every(t=>/^[a-f0-9]{48}$/.test(t)));});
test('report contains every record class and no private notes or unsafe markup',()=>{const c=fixture(),p=c.projects.p;p.name='<script>danger</script>';const html=buildProjectReport({client:c,project:p,approvals:[{title:'APPROVAL',desc:'Please confirm',confirmation:{confirmedAt:'2026-09-23T00:00:00.000Z'}}],feedback:[{message:'FEEDBACK',response:'REPLY'}],signature:{name:'SIGNER',signedAt:'2026-09-23T00:00:00.000Z',termsSnapshot:agreementTerms(p)},logoUrl:'https://example.invalid/logo.png'});for(const expected of ['APPROVAL','FEEDBACK','REPLY','SIGNER','Payment record','Production &amp; delivery','PUBLIC NOTE','proof.png'])assert.ok(html.includes(expected)||expected==='Production &amp; delivery'&&html.includes('Production & delivery'));assert.ok(!html.includes('PRIVATE NOTE'));assert.ok(!html.includes('<script>danger'));assert.ok(html.includes('&lt;script&gt;danger'));assert.ok(html.includes('window.print()'));assert.ok(html.includes('</script>'));});
