#!/usr/bin/env node
// VisionFlow Apps Script Build — bundles modules into a standalone Code.gs
// Usage: node backend/apps-script/runtime/build.mjs
//
// Reads Codex-owned input modules WITHOUT modifying them.
// Output: backend/apps-script/runtime/Code.gs
//
// This is a narrow deterministic build with no external dependencies.
// It reads source files, strips import/export statements, and concatenates
// them in dependency order into a single Apps Script V8-compatible file.

import { readFileSync, writeFileSync } from 'node:fs';
import { Script } from 'node:vm';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..', '..', '..');

// ── Source files in dependency order ──────────────────────────────
const sources = [
  { path: 'portal/review-policy.js', label: 'review-policy' },
  { path: 'portal/data.js', label: 'data-helpers', extractOnly: ['sameRecord', 'currentMaster', 'projectAcknowledged'] },
  { path: 'backend/review-engine.mjs', label: 'review-engine' },
  { path: 'portal/notification-events.js', label: 'notification-events' },
  { path: 'portal/payment-notification.js', label: 'payment-notification' },
  { path: 'backend/apps-script/payment-document.mjs', label: 'payment-document' },
  { path: 'backend/apps-script/review-context.mjs', label: 'review-context' },
  { path: 'backend/apps-script/source-binding.mjs', label: 'source-binding' },
  { path: 'backend/apps-script/review-worker.mjs', label: 'review-worker' },
  { path: 'backend/apps-script/worker.mjs', label: 'worker' },
  { path: 'backend/apps-script/runtime/adapters.mjs', label: 'adapters' },
  { path: 'backend/apps-script/runtime/readiness.mjs', label: 'readiness' },
];

function sha256(content) {
  return createHash('sha256').update(content).digest('hex');
}

// ── Strip imports and exports ─────────────────────────────────────
function stripModuleSyntax(code, label) {
  let result = code;

  // Remove import statements
  result = result.replace(/^import\s+\{[^}]*\}\s+from\s+['"][^'"]+['"];?\s*$/gm, '');
  result = result.replace(/^import\s+['"][^'"]+['"];?\s*$/gm, '');

  // Remove export keywords but keep the declarations
  result = result.replace(/^export\s+(function|const|let|var|class|async\s+function)\s/gm, '$1 ');
  result = result.replace(/^export\s+\{[^}]*\};?\s*$/gm, '');
  result = result.replace(/^export\s+default\s+/gm, '');

  // Remove Node.js module.exports blocks
  result = result.replace(/if\s*\(\s*typeof\s+module\s*!==\s*'undefined'[\s\S]*?module\.exports[\s\S]*?\}\s*$/gm, '');

  if (label === 'worker') result = result.replace(/^function do(Get|Post)\(/gm, 'function workerDo$1(');
  return result;
}

// ── Extract specific functions from data.js ───────────────────────
function extractFunctions(code, functionNames) {
  const lines = code.split('\n');
  const extracted = [];

  for (const name of functionNames) {
    // Find function declaration line
    const startIdx = lines.findIndex(l =>
      new RegExp(`^\\s*(?:export\\s+)?function\\s+${name}\\b`).test(l)
    );
    if (startIdx === -1) {
      throw new Error(`Required function ${name} not found in data.js`);
    }

    // Track braces to find end
    let depth = 0;
    let endIdx = startIdx;
    for (let i = startIdx; i < lines.length; i++) {
      for (const ch of lines[i]) {
        if (ch === '{') depth++;
        if (ch === '}') depth--;
      }
      if (depth <= 0 && i > startIdx) {
        endIdx = i;
        break;
      }
    }

    let block = lines.slice(startIdx, endIdx + 1).join('\n');
    block = block.replace(/^export\s+/, '');
    extracted.push(block);
  }

  return extracted.join('\n\n');
}

// ── Build ─────────────────────────────────────────────────────────
console.log('VisionFlow Apps Script Build');
console.log('===========================\n');

const inputHashes = {};
const outputParts = [];

// Header
outputParts.push(`// VisionFlow Trusted Backend — Apps Script V8 Runtime
// AUTO-GENERATED by build.mjs — DO NOT EDIT DIRECTLY
// Reproducible build: input SHA-256 values are embedded below.
// All async/await preserved. Security checks preserved.
//
// Global entry points: doGet(e), doPost(e), scheduledWorker(), ownerReadinessCheck()
// Config: Script Properties (ENABLED, REVIEW_STATE_READY, PROJECT_ID, ADMIN_UID, ACTIVATION_BOUNDARY)
// Default state: DISABLED (enabled=false, reviewStateReady=false)
// No trigger auto-created. No fallback enables mail when config absent.
`);

for (const source of sources) {
  const filePath = join(repoRoot, source.path);
  const content = readFileSync(filePath, 'utf-8');
  const hash = sha256(content);
  inputHashes[source.path] = hash;

  console.log(`  ${source.path}: ${hash.slice(0, 16)}...`);

  outputParts.push(`\n// ═══════════════════════════════════════════════════════════════════`);
  outputParts.push(`// Source: ${source.path} (SHA-256: ${hash})`);
  outputParts.push(`// ═══════════════════════════════════════════════════════════════════\n`);

  if (source.extractOnly) {
    outputParts.push(extractFunctions(content, source.extractOnly));
  } else {
    outputParts.push(stripModuleSyntax(content, source.label));
  }
}

// ── Global entry points ───────────────────────────────────────────
outputParts.push(`
// ═══════════════════════════════════════════════════════════════════
// Global Apps Script Entry Points
// ═══════════════════════════════════════════════════════════════════

// doGet: non-sensitive health — returns ContentService JSON
function doGet(e) {
  var result = workerDoGet(e, { config: loadConfig_runtime() });
  return ContentService.createTextOutput(JSON.stringify(result))
    .setMimeType(ContentService.MimeType.JSON);
}

// doPost: fails closed — returns ContentService JSON
function doPost(e) {
  var result = workerDoPost(e, { config: loadConfig_runtime(), firestore: null });
  return ContentService.createTextOutput(JSON.stringify(result))
    .setMimeType(ContentService.MimeType.JSON);
}

// Scheduled worker — called by time-driven trigger (NOT auto-created)
async function scheduledWorker() {
  var config = loadConfig_runtime();
  if (config.enabled !== true) {
    Logger.log('Worker disabled. Set ENABLED=true in Script Properties after verification.');
    return { disabled: true };
  }
  if (!validateConfig(config).valid) throw new Error('Worker configuration incomplete.');
  var firestore = createFirestoreAdapter_runtime();
  var mail = createMailAdapter_runtime(firestore);
  var clock = createClockAdapter();

  // Process outbox events
  var outboxResult = await processOutbox({ firestore: firestore, mail: mail, clock: clock, config: config });
  Logger.log('Outbox: ' + JSON.stringify({ ok: outboxResult.ok, processed: outboxResult.processed }));

  // Process review timers
  var reviewResult = await settleReviewTimers({ firestore: firestore, clock: clock, config: config });
  Logger.log('Reviews: ' + JSON.stringify({ processed: reviewResult.processed }));
  return { outbox: outboxResult, reviews: reviewResult };
}

// ── Runtime adapter constructors (use real Apps Script globals) ────
function createFirestoreAdapter_runtime() {
  return createFirestoreAdapter({
    urlFetch: UrlFetchApp,
    scriptApp: ScriptApp,
    projectId: PropertiesService.getScriptProperties().getProperty('PROJECT_ID') || '',
  });
}

function createMailAdapter_runtime(firestore) {
  var adapter = createMailAdapter({ mailApp: MailApp, session: typeof Session === 'undefined' ? null : Session, expectedSender: loadConfig_runtime().expectedSender,
    paymentAttachment: function(document) { firestore.checkBudget(); return createPaymentAttachment(document, {urlFetch: UrlFetchApp, utilities: Utilities, htmlService: HtmlService}); }
  });
  return {
    readiness: adapter.readiness,
    remainingQuota: adapter.remainingQuota,
    send: async function(message) { firestore.checkBudget(); return await adapter.send(message); }
  };
}

function loadConfig_runtime() {
  return loadConfig({ propertiesService: PropertiesService });
}

// Owner/editor-only diagnostic; never called by the public web handlers.
async function ownerReadinessCheck() {
  var report = await inspectRuntimeReadiness({
    config: loadConfig_runtime(), firestore: createFirestoreAdapter_runtime(),
    scriptApp: ScriptApp, session: Session, mailApp: MailApp
  });
  Logger.log(JSON.stringify(report));
  return report;
}

// ── Setup instructions (disabled by default) ──────────────────────
// 1. Open Script Properties: Project Settings → Script Properties
// 2. Set: PROJECT_ID = visionflow-bd
// 3. Set: ADMIN_UID = m1PGSw7ViEb1xOJoj8INQllra3p1
// 4. Set: ACTIVATION_BOUNDARY = <ISO timestamp of first activation>
// 5. Set: ENABLED = true (ONLY after all prerequisites verified)
// 6. Set: REVIEW_STATE_READY = true (ONLY after portal/rules review integration complete)
// 7. Create time-driven trigger: Edit → Triggers → scheduledWorker, every 5 minutes
// 8. Grant requested scopes when prompted
//
// Prerequisites (all must be independently verified before enabling):
// - IAM: visionflow.agency.bd@gmail.com has datastore.user on visionflow-bd project
// - Firestore rules include portal_outbox, portal_backend_events, portal_reviews
// - Portal enqueues outbox events atomically with state changes
// - Portal implements shared review state under portal_public/{token}/reviews/{id}
// - Owner has consented to all declared OAuth scopes
`);

const outputContent = outputParts.join('\n');
new Script(outputContent, { filename: 'Code.gs' });
const outputPath = join(__dirname, 'Code.gs');
writeFileSync(outputPath, outputContent, 'utf-8');

const outputHash = sha256(outputContent);

console.log(`\nOutput: ${outputPath}`);
console.log(`Output SHA-256: ${outputHash}`);
console.log(`Output size: ${outputContent.length} bytes`);
console.log(`\nInput hashes:`);
for (const [path, hash] of Object.entries(inputHashes)) {
  console.log(`  ${path}: ${hash}`);
}
console.log('\nBuild complete. NOT DEPLOYED.');
