import { esc, money, safeUrl, signatureImage, metrics, itemsOf, LABEL } from './data.js';

const date = value => { const d=new Date(value); return Number.isNaN(d.valueOf())?String(value||'—'):d.toLocaleString('en-GB'); };
const url = (value,label) => safeUrl(value)?`<a href="${esc(safeUrl(value))}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`:'';
const td = value => `<td>${esc(value||'—')}</td>`;

export function buildProjectReport({client,project,items=itemsOf(project),approvals=[],signature=null,feedback=[],logoUrl='',generatedAt=new Date().toISOString()}) {
  const m=metrics(project),signedTerms=signature?.termsSnapshot;
  const paymentRows=(project.payments||[]).map(p=>`<tr>${td(p.date)}${td(p.type)}${td(money(p.amount))}<td>${esc(p.note||'—')}${safeUrl(p.proofUrl)?`<br>${url(p.proofUrl,'View proof')}<br><img class="proof" src="${esc(safeUrl(p.proofUrl))}" alt="Payment proof">`:''}</td></tr>`).join('');
  const itemRows=items.map(i=>`<tr>${td(i.n)}<td><strong>${esc(i.b||'Awaiting script')}</strong><br>${esc(i.t||'')}</td>${td(LABEL[i.s]||i.s)}${td(i.sd)}${td(i.dd)}${td(i.dur)}<td>${[url(i.dl,'Final video'),url(i.scriptUrl,'Script'),url(i.avatarUrl,'Avatar'),url(i.referenceUrl,'Reference')].filter(Boolean).join('<br>')||'—'}${i.clientNote?`<br>${esc(i.clientNote)}`:''}</td></tr>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>${esc(project.name)} — Vision Flow project record</title><style>
  *{box-sizing:border-box}body{margin:0;background:#e9edf3;color:#17233a;font:13px/1.5 Arial,sans-serif}.toolbar{position:sticky;top:0;padding:14px 20px;background:#10263c;color:#fff;display:flex;align-items:center;justify-content:space-between;gap:12px;z-index:2}.toolbar button{border:0;border-radius:8px;background:#f36b4e;color:white;padding:12px 18px;font-weight:700;cursor:pointer}.sheet{max-width:1000px;margin:24px auto;padding:40px;background:white;box-shadow:0 10px 30px #10263c18}header{display:flex;align-items:center;justify-content:space-between;gap:20px;border-bottom:3px solid #ec6a51;padding-bottom:22px}header img{width:140px;max-height:85px;object-fit:contain}header h1{margin:0;font-size:22px;color:#174758}.right{text-align:right}.eyebrow{font-size:10px;letter-spacing:1.5px;color:#6f7a8b;text-transform:uppercase}h2{font-size:18px;margin:28px 0 10px;color:#174758}h3{font-size:14px;margin:0 0 8px}p{margin:5px 0 12px}.muted{color:#65718a}.summary{display:grid;grid-template-columns:repeat(5,1fr);gap:9px;margin:20px 0}.summary div{border:1px solid #dbe3ed;background:#f7f9fc;padding:13px;border-radius:8px}.summary small{display:block;color:#617087}.summary strong{display:block;font-size:17px;margin-top:6px}table{border-collapse:collapse;width:100%;font-size:11px}th,td{padding:9px 8px;text-align:left;border-bottom:1px solid #dce3ec;vertical-align:top;overflow-wrap:anywhere}th{background:#eff4f8;color:#405975}a{color:#156883}.proof{max-width:130px;max-height:85px;object-fit:contain;margin-top:5px}.signature{max-width:260px;max-height:100px}.record{border:1px solid #dce3ec;border-radius:8px;padding:16px;margin:12px 0}.pre{white-space:pre-wrap}.scope{display:grid;grid-template-columns:1fr 1fr;gap:14px}.footer{margin-top:32px;border-top:1px solid #dce3ec;padding-top:14px;font-size:10px;color:#63728a}@page{size:A4;margin:14mm 12mm}@media print{body{background:#fff;font-size:11px}.toolbar{display:none}.sheet{padding:0;box-shadow:none;margin:0;max-width:none}table{font-size:9px}th,td{padding:7px 5px}thead{display:table-header-group}tr,.record,.summary,header{break-inside:avoid}h2{break-after:avoid}a{text-decoration:underline}.summary strong{font-size:14px}header img{width:120px}*{-webkit-print-color-adjust:exact;print-color-adjust:exact}}@media(max-width:650px){.sheet{padding:20px;margin:0}.summary{grid-template-columns:repeat(2,1fr)}.scope{grid-template-columns:1fr}.table-scroll{overflow:auto}.toolbar{font-size:11px}header{align-items:flex-start}header img{width:100px}}
  </style></head><body><div class="toolbar"><span>Project record preview · Check details, then print or save as PDF.</span><button id="printButton">Print / save PDF</button></div><main class="sheet"><header><div>${safeUrl(logoUrl)?`<img src="${esc(safeUrl(logoUrl))}" alt="Vision Flow">`:'<h1>Vision Flow</h1>'}<p class="eyebrow">Creative production · Project record</p></div><div class="right"><h1>Project statement</h1><p class="muted">Generated ${esc(date(generatedAt))}</p><small>visionflow-bd.github.io</small></div></header>
  <h2>${esc(project.name)}</h2><p><strong>Client:</strong> ${esc(client.name)} · <strong>Status:</strong> ${esc(LABEL[project.status]||project.status||'Active')}</p><p class="muted">${m.total} deliverables at ${money(project.rate)} each · ${m.done} complete · ${m.total-m.done} remaining</p><section class="summary"><div><small>Complete</small><strong>${m.percent}%</strong></div><div><small>Delivered</small><strong>${m.done}/${m.total}</strong></div><div><small>Budget</small><strong>${money(m.budget)}</strong></div><div><small>Paid</small><strong>${money(m.paid)}</strong></div><div><small>${m.due<0?'Credit':'Due'}</small><strong>${money(Math.abs(m.due))}</strong></div></section>
  <h2>Scope, milestones & payment terms</h2><p class="pre">${esc(project.scope||'No additional scope recorded.')}</p><div class="scope"><p><strong>Target date:</strong> ${esc(project.deadline||'Not set')}<br><strong>Weekly target:</strong> ${esc(project.weeklyTarget||'Not set')}</p><p class="pre"><strong>Milestone:</strong> ${esc(project.milestoneText||'Not set')}</p></div><p class="pre">${esc(project.terms||'No additional terms recorded.')}</p><p>${url(project.sourceScriptUrl,'Source scripts')} ${url(project.avatarFolderUrl,'Character references')}</p>
  <h2>Payment record</h2><table><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Note / proof</th></tr></thead><tbody>${paymentRows||'<tr><td colspan="4">No payment recorded.</td></tr>'}</tbody></table>
  <h2>Client approvals</h2>${approvals.map(a=>`<div class="record"><h3>${esc(a.title)}</h3><p class="pre">${esc(a.desc)}</p><small>${a.confirmation?'Confirmed '+esc(date(a.confirmation.confirmedAt)):'Awaiting confirmation'}</small></div>`).join('')||'<p>No approval requests recorded.</p>'}
  <h2>Agreement signature</h2>${signature?`<div class="record"><h3>${esc(signature.displayName||signature.review?.displayName||signature.name)}</h3><p>Signed ${esc(date(signature.signedAt))} · ${esc(signature.review?.state||'Awaiting verification')}${signature.outdated?' · Current project terms differ from the signed version':''}</p>${signatureImage(signature.image)?`<img class="signature" src="${signatureImage(signature.image)}" alt="Client signature">`:''}${signature.review?.message?`<p>${esc(signature.review.message)}</p>`:''}${signedTerms?`<h3>Terms captured at signing</h3><p>${esc(signedTerms.projectName)} · ${signedTerms.totalItems} deliverables · Budget ${money(signedTerms.budget)}</p><p class="pre">${esc(signedTerms.scope)}<br>${esc(signedTerms.terms)}<br>${esc(signedTerms.milestoneText)}</p><p>Target date: ${esc(signedTerms.deadline||'Not set')} · Weekly target: ${signedTerms.weeklyTarget||'Not set'}</p><small>Record fingerprint: ${esc(signature.termsDigest||'Not recorded')}</small>`:'<p class="muted">Legacy signature: original terms snapshot was not captured.</p>'}</div>`:'<p>No signature has been recorded.</p>'}
  <h2>Production & delivery details</h2><div class="table-scroll"><table><thead><tr><th>#</th><th>Breed / title</th><th>Status</th><th>Started</th><th>Delivered</th><th>Duration</th><th>Files / notes</th></tr></thead><tbody>${itemRows||'<tr><td colspan="7">No production items.</td></tr>'}</tbody></table></div>
  <h2>Feedback & revisions</h2>${feedback.map(f=>`<div class="record"><h3>${f.itemNumber?'Video '+esc(f.itemNumber):'Project-wide'} · ${esc(f.requestType||'Feedback')}</h3><p class="pre">${esc(f.displayMessage??f.message)}</p><p class="muted">${esc(date(f.submittedAt))} · ${esc(f.status||'new')}</p>${f.response?`<p class="pre"><strong>Vision Flow:</strong> ${esc(f.response)}</p>`:''}</div>`).join('')||'<p>No feedback requests recorded.</p>'}
  <footer class="footer">Generated from the Vision Flow project workspace on ${esc(date(generatedAt))}. This report reflects the records available at generation time. Payment proof and delivery links refer to the attached source records. Keep a copy alongside the original agreement and communications.</footer></main><script>document.getElementById('printButton').addEventListener('click',function(){window.print()});<\/script></body></html>`;
}
